In [1]:


import pandas as pd

In [2]:
wiki_sci_parquets = "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences"
out_dir = "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences_index"

In [6]:
import os 
import faiss
import numpy as np
from tqdm import tqdm

# build index from --wiki-sci-parquets directory
parquet_files = [os.path.join(wiki_sci_parquets, f) for f in os.listdir(wiki_sci_parquets) if f.endswith('.parquet')]
wiki_sci_df = pd.read_parquet(parquet_files[0])

sentence_embeddings = np.stack(wiki_sci_df['sentences_embd'].values).astype('float32')
sentence_index = faiss.IndexFlatIP(sentence_embeddings.shape[1])
sentence_index.add(sentence_embeddings)

sentences = list(wiki_sci_df['sentences'].values)
del wiki_sci_df

print("Creating faiss embedding index for wiki sentences ... ")
for file_path in tqdm(parquet_files[1:]):
    df_tmp = pd.read_parquet(file_path)

    sentence_embeddings = np.stack(df_tmp['sentences_embd'].values).astype('float32')
    sentence_index.add(sentence_embeddings)

    sentences.extend(list(df_tmp['sentences'].values))
    
    del df_tmp

Creating faiss embedding index for wiki sentences ... 


100%|██████████| 30/30 [00:31<00:00,  1.04s/it]


In [8]:
# save sentence_index to "out_dir"
faiss.write_index(sentence_index, os.path.join(out_dir, 'sentence_index.faiss'))

In [25]:
import pandas as pd

df = pd.read_csv("/tmp/test_1_fast.csv")
df

id                                             prompt   
0      0  Context: The homogeneously distributed mass of...  \
1      1  Context: To describe these systems, it is conv...   
2      2  Context: "Caput Medusae" [Latin] means "Head o...   
3      3  Context:    (Another way to avoid the infinity...   
4      4  Context: The finer the grating spacing, the gr...   
..   ...                                                ...   
195  195  Context:  Then the bending moments  at the thr...   
196  196  Context: Most liquids such as hydraulic oils w...   
197  197  Context: Instead, an examination of the micros...   
198  198  Context: Under Sir Isaac Newton's -year-old la...   
199  199  Context: Einstein's prediction was confirmed b...   

                                                     A   
0    MOND is a theory that reduces the observed mis...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol was reconstructed as a fe...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem expresses the relatio...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often solidify, bec...   
198  Mass is a property that determines the weight ...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     B   
0    MOND is a theory that increases the discrepanc...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol is a representation of th...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often crystallize-o...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     C   
0    MOND is a theory that explains the missing bar...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol is a representation of a ...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem describes the relatio...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often dissolve, bec...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     D   
0    MOND is a theory that reduces the discrepancy ...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol represents three interloc...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often liquefy, beco...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     E  
0    MOND is a theory that eliminates the observed ...  
1    Dynamic scaling refers to the evolution of sel...  
2    The triskeles symbol is a representation of th...  
3    Regularizing the mass-energy of an electron wi...  
4    The angular spacing of features in the diffrac...  
..                                                 ...  
195  The three moment theorem is used to derive the...  
196  

In [28]:
indx = 2

print(df.iloc[indx]['prompt'])
print("----"*200)

print(df.iloc[indx]['A'])
print("----"*200)
print(df.iloc[indx]['B'])
print("----"*200)
print(df.iloc[indx]['C'])
print("----"*200)
print(df.iloc[indx]['D'])
print("----"*200)
print(df.iloc[indx]['E'])
print("----"*200)

Context: "Caput Medusae" [Latin] means "Head of Medusa".

References

Veins of the torso. The study of the Bradford Royal Infirmary found that dog bites were twice as common during a full moon, whereas the study conducted by the public hospitals in Australia found that they were less likely.

The symbol of the Triple Goddess is drawn with the circular image of the full moon in the center flanked by a left facing crescent and right facing crescent, representing a maiden, mother and crone archetype.

Full moon names
Historically, month names are names of moons (lunations, not necessarily full moons) in lunisolar calendars. a victory involving one's own ruin).

Three medical symbols involving snakes that are still used today are Bowl of Hygieia, symbolizing pharmacy, and the Caduceus and Rod of Asclepius, which are symbols denoting medicine in general.

One of the etymologies proposed for the common female first name Linda is that it might derive from Old German Lindi or Linda, meaning a 

In [47]:
df.head()

id                                             prompt   
0   0  Context: Misleading results could be easily pr...  \
1   1  Context: Slopes less negative than -3 are also...   
2   2  Context: The Ancient Chinese (mainly in the Sh...   
3   3  Context: In quantum field theory, the pole mas...   
4   4  Context: Advanced algorithms have been develop...   

                                                   A   
0  MOND is a theory that reduces the observed mis...  \
1  Dynamic scaling refers to the evolution of sel...   
2  The triskeles symbol was reconstructed as a fe...   
3  Regularizing the mass-energy of an electron wi...   
4  The angular spacing of features in the diffrac...   

                                                   B   
0  MOND is a theory that increases the discrepanc...  \
1  Dynamic scaling refers to the non-evolution of...   
2  The triskeles symbol is a representation of th...   
3  Regularizing the mass-energy of an electron wi...   
4  The angular spacing of features in the diffrac...   

                                                   C   
0  MOND is a theory that explains the missing bar...  \
1  Dynamic scaling refers to the evolution of sel...   
2  The triskeles symbol is a representation of a ...   
3  Regularizing the mass-energy of an electron wi...   
4  The angular spacing of features in the diffrac...   

                                                   D   
0  MOND is a theory that reduces the discrepancy ...  \
1  Dynamic scaling refers to the non-evolution of...   
2  The triskeles symbol represents three interloc...   
3  Regularizing the mass-energy of an electron wi...   
4  The angular spacing of features in the diffrac...   

                                                   E answer   
0  MOND is a theory that eliminates the observed ...      D  \
1  Dynamic scaling refers to the evolution of sel...      A   
2  The triskeles symbol is a representation of th...      A   
3  Regularizing the mass-energy of an electron wi...      C   
4  The angular spacing of features in the diffrac...      D   

                                       prompt_joined   
0  Which of the following statements accurately d...  \
1  Which of the following is an accurate definiti...   
2  Which of the following statements accurately d...   
3  What is the significance of regularization in ...   
4  Which of the following statements accurately d...   

                                         embd_prompt   
0  [-0.00616957  0.00835114 -0.01575178 ...  0.00...  \
1  [-0.00293011  0.01273543  0.01158911 ...  0.00...   
2  [-0.01662981 -0.00363794  0.00417407 ...  0.01...   
3  [ 0.00753833  0.00607232  0.02841755 ...  0.00...   
4  [-0.0079557  -0.00498035  0.00022749 ...  0.02...   

                                 parquet_0_sentences   
0  ['Alternatives to the dark matter hypothesis i...  \
1  ['In the study of partial differential equatio...   
2  ['In it, the character Meton of Athens mention...   
3  ['The process of renormalization might be thou...   
4  ['The difference between the separable and rad...   

                                 parquet_0_distances   
0  [[0.87471354 0.85101813 0.8447482  0.8375474  ...  \
1  [[0.85100216 0.8449844  0.8314541  0.8306275  ...   
2  [[0.7963717  0.79179496 0.78832126 0.7876787  ...   
3  [[0.8750266  0.8643717  0.85752195 0.8567778  ...   
4  [[0.8513332  0.84804183 0.84772354 0.8445657  ...   

                                 parquet_1_sentences   
0  ['It has also been suggested that light dark m...  \
1  ['Nyquist stability criterion) or dynamic equi...   
2  ['As a result of precession over the centuries...   
3  ['The corrections from the Yukawa couplings ar...   
4  ['In order to make this evident, we will write...   

                                 parquet_1_distances   
0  [[0.84666    0.84388214 0.8411464  0.8374137  ...  \
1  [[0.8307599  0.8288529  0.82864517 0.8261934  ...   
2  [[0.8215388  0.8092987  0.80302006 0.800843   ...   
3  [[0

In [50]:
import numpy as np
csv = df

# Now that we have a full csv with all the sentences, we can create the context
columns_distances = [c for c in csv.columns if c.endswith('_distances')]
columns_distances_n = [int(c.split('_')[1]) for c in columns_distances]
print(columns_distances)
sorted_indices = np.argsort(columns_distances_n)
columns_distances = [columns_distances[i] for i in sorted_indices]

columns_sentences = [c for c in csv.columns if c.endswith('_sentences')]
columns_sentences_n = [int(c.split('_')[1]) for c in columns_sentences]
print(columns_sentences)
sorted_indices = np.argsort(columns_sentences_n)
columns_sentences = [columns_sentences[i] for i in sorted_indices]

distances_all = csv[columns_distances].values
sentences_all = csv[columns_sentences].values

['parquet_0_distances', 'parquet_1_distances']
['parquet_0_sentences', 'parquet_1_sentences']


array([['[[0.87471354 0.85101813 0.8447482  0.8375474  0.83716583 0.8359148\n  0.8342341  0.83152777 0.8295169  0.82920676]]',
        '[[0.84666    0.84388214 0.8411464  0.8374137  0.83394516 0.8336712\n  0.83321077 0.83087933 0.8295949  0.8286002 ]]'],
       ['[[0.85100216 0.8449844  0.8314541  0.8306275  0.828408   0.82825124\n  0.8276799  0.8275402  0.8266687  0.8264006 ]]',
        '[[0.8307599  0.8288529  0.82864517 0.8261934  0.82616574 0.82552594\n  0.8252254  0.8234102  0.8208     0.8202794 ]]'],
       ['[[0.7963717  0.79179496 0.78832126 0.7876787  0.7873739  0.7855117\n  0.7846902  0.78355944 0.7832032  0.7814837 ]]',
        '[[0.8215388  0.8092987  0.80302006 0.800843   0.7988454  0.79739904\n  0.79648787 0.7959971  0.7949551  0.7940355 ]]'],
       ['[[0.8750266  0.8643717  0.85752195 0.8567778  0.85338265 0.84848577\n  0.8484496  0.8467854  0.84624505 0.8439701 ]]',
        '[[0.8589061  0.8524786  0.85184246 0.8502383  0.8473465  0.8463538\n  0.84556913 0.8454996  0.8

In [6]:
import pandas as pd

df = pd.read_parquet("/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences/wiki_sci_embd_clusters_sentences_0.parquet")
df

sentences   
0      The Ulakhan Fault is a left-lateral moving tra...  \
1       It runs from a triple junction in the Chersky...   
2      From the offset of dated geomorphological feat...   
3      The analysis of fault scarps along the fault z...   
4      Tripodal ligands are tri- and tetradentate lig...   
...                                                  ...   
99995   During the task, animal subjects are operant ...   
99996   Reinforcement (through the use of the drug) o...   
99997  Drug dosing in self-administration studies is ...   
99998  This is an important element of creating a dis...   
99999  In summary, the effects of response-dependent ...   

                                          sentences_embd  
0      [-0.028980039, 0.03867789, -0.022340525, 0.009...  
1      [0.0011227154, 0.042402018, -0.027796535, 0.01...  
2      [-0.003369958, 0.061145917, -0.006183491, 0.01...  
3      [0.008782866, 0.047354806, 0.004257064, 0.0273...  
4      [0.0016080242, -0.0003384063, 0.022075392, 0.0...  
...                                                  ...  
99995  [0.0012561153, 0.011253346, -0.009115973, 0.01...  
99996  [-0.0032600083, 0.0022629944, -0.010305869, 0....  
99997  [-0.0027855465, 0.017488176, 0.004970365, 0.01...  
99998  [-0.027314313, 0.03127125, -0.010550045, 0.014...  
99999  [-0.014868274, 0.010800852, 0.006291764, 0.010...  

[100000 rows x 2 columns]

In [27]:
import numpy as np
x = np.stack(df['sentences_embd'].values).astype('float32')

# run kmeans with 1000 clusters
import faiss

kmeans = faiss.Kmeans(x.shape[1], 400, niter=200, verbose=True)
kmeans.train(x)




Clustering 100000 points in 1024D to 400 clusters, redo 1 times, 200 iterations
  Preprocessing in 0.03 s


KeyboardInterrupt: 

In [18]:
x_example = x[0]
# find the 10 nearest neighbors of x_example
D, I = kmeans.index.search(x_example.reshape(1, -1), 10)
I

array([[6739,   15, 9757,  641, 9232, 4410, 3882, 8956, 2042, 1839]])

In [19]:
# save kmeans to disk
faiss.write_index(kmeans.index, "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences/wiki_sci_embd_clusters_0.faiss")



In [20]:
del kmeans


In [21]:

# load kmeans from disk
kmeans = faiss.read_index("/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences/wiki_sci_embd_clusters_0.faiss")

In [22]:
!ls -lah "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences/wiki_sci_embd_clusters_0.faiss"

-rw-rw-r-- 1 viktor viktor 40M ruj   2 00:56 /home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences/wiki_sci_embd_clusters_0.faiss


In [28]:
x = np.stack(df['sentences_embd'].values).astype('float32')

d = x.shape[1]  # dimensionality of the data
k = 1000  # number of clusters
niter = 20  # number of iterations


kmeans = faiss.Kmeans(d, k, niter=niter, verbose=True)
kmeans.index = faiss.IndexFlatIP(d)
kmeans.train(x)


Clustering 100000 points in 1024D to 400 clusters, redo 1 times, 200 iterations
  Preprocessing in 0.05 s
  Iteration 199 (26.41 s, search 24.89 s): objective=19325.8 imbalance=1.133 nsplit=0       


19325.83203125

In [30]:
D, I = kmeans.index.search(x, 1)
I

array([[ 15],
       [ 15],
       [ 15],
       ...,
       [146],
       [ 43],
       [ 43]])

In [36]:
D

array([[0.21458101],
       [0.28724134],
       [0.20163393],
       ...,
       [0.18652081],
       [0.17933726],
       [0.18469119]], dtype=float32)

In [31]:
faiss.write_index(kmeans.index, "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences_index/wiki_sci_embd_clusters_0.faiss")

In [32]:
del kmeans

In [33]:
!ls -lah "/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences_index"

total 1,6M
drwxrwxr-x  2 viktor viktor 4,0K ruj   2 01:02 .
drwxrwxr-x 22 viktor viktor 4,0K ruj   2 01:02 ..
-rw-rw-r--  1 viktor viktor 1,6M ruj   2 01:02 wiki_sci_embd_clusters_0.faiss


In [34]:
# load kmeans from disk
kmeans = faiss.read_index("/home/viktor/Documents/kaggle/kaggle_llm/data/wikipedia_pages2_w_embd_sentences_index/wiki_sci_embd_clusters_0.faiss")

In [8]:
import pandas as pd


df = pd.read_parquet("/tmp/test.parquet")
df

id                                             prompt   
0      0  Which of the following statements accurately d...  \
1      1  Which of the following is an accurate definiti...   
2      2  Which of the following statements accurately d...   
3      3  What is the significance of regularization in ...   
4      4  Which of the following statements accurately d...   
..   ...                                                ...   
195  195  What is the relation between the three moment ...   
196  196  What is the throttling process, and why is it ...   
197  197  What happens to excess base metal as a solutio...   
198  198  What is the relationship between mass, force, ...   
199  199  What did Arthur Eddington discover about two o...   

                                                     A   
0    MOND is a theory that reduces the observed mis...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol was reconstructed as a fe...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem expresses the relatio...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often solidify, bec...   
198  Mass is a property that determines the weight ...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     B   
0    MOND is a theory that increases the discrepanc...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol is a representation of th...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often crystallize-o...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     C   
0    MOND is a theory that explains the missing bar...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol is a representation of a ...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem describes the relatio...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often dissolve, bec...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     D   
0    MOND is a theory that reduces the discrepancy ...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol represents three interloc...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often liquefy, beco...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     E answer   
0    MOND is a theory that eliminates the observed ...      D  \
1    Dynamic scaling refers to the evolution of sel...      A   
2    The triskeles symbol is a representation of th...      A   
3    Regularizing the mass-energy of an electron wi...      C   
4    The angular spacing of features in the diffrac...      D   
..                                                 ...    ...   
195  T

In [10]:
import numpy as np

# Now that we have a full df with all the sentences, we can create the context
columns_distances = [c for c in df.columns if c.endswith('_distances')]
columns_distances_n = [int(c.split('_')[1]) for c in columns_distances]
sorted_indices = np.argsort(columns_distances_n)
columns_distances = [columns_distances[i] for i in sorted_indices]

columns_sentences = [c for c in df.columns if c.endswith('_sentences')]
columns_sentences_n = [int(c.split('_')[1]) for c in columns_sentences]
sorted_indices = np.argsort(columns_sentences_n)
columns_sentences = [columns_sentences[i] for i in sorted_indices]

distances_all = np.stack([np.stack(x) for x in df[columns_distances].values]) # (n_rows, n_parquets, n_sentences)
sentences_all = np.stack([np.stack(x) for x in df[columns_sentences].values]) # (n_rows, n_parquets, n_sentences)

n_rows, n_parquets, n_sentences = distances_all.shape
distances_all = np.reshape(distances_all, (n_rows, n_sentences * n_parquets))
sentences_all = np.reshape(sentences_all, (n_rows, n_sentences * n_parquets))


In [18]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
x[0]

array([[1, 2],
       [3, 4]])

In [17]:
n_rows, n_parquets, n_sentences = x.shape
x = np.reshape(x, (n_rows, n_sentences * n_parquets))
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
import pandas as pd


df = pd.read_csv("/tmp/test_1_fast.csv")
df

id                                             prompt   
0      0  Context: The homogeneously distributed mass of...  \
1      1  Context: To describe these systems, it is conv...   
2      2  Context: "Caput Medusae" [Latin] means "Head o...   
3      3  Context:    (Another way to avoid the infinity...   
4      4  Context: The finer the grating spacing, the gr...   
..   ...                                                ...   
195  195  Context:  Then the bending moments  at the thr...   
196  196  Context: Most liquids such as hydraulic oils w...   
197  197  Context: Instead, an examination of the micros...   
198  198  Context: Under Sir Isaac Newton's -year-old la...   
199  199  Context: Einstein's prediction was confirmed b...   

                                                     A   
0    MOND is a theory that reduces the observed mis...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol was reconstructed as a fe...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem expresses the relatio...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often solidify, bec...   
198  Mass is a property that determines the weight ...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     B   
0    MOND is a theory that increases the discrepanc...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol is a representation of th...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often crystallize-o...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     C   
0    MOND is a theory that explains the missing bar...  \
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol is a representation of a ...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem describes the relatio...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often dissolve, bec...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     D   
0    MOND is a theory that reduces the discrepancy ...  \
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol represents three interloc...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often liquefy, beco...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     E  
0    MOND is a theory that eliminates the observed ...  
1    Dynamic scaling refers to the evolution of sel...  
2    The triskeles symbol is a representation of th...  
3    Regularizing the mass-energy of an electron wi...  
4    The angular spacing of features in the diffrac...  
..                                                 ...  
195  The three moment theorem is used to derive the...  
196  

In [33]:
df['prompt_len'] = df['prompt'].apply(lambda x: len(x))
df['prompt_len'].max()

12876

In [32]:
df['prompt'] = 3*df['prompt']

In [ ]:
df.to_csv("/tmp/test_1_fast_2.csv")
